---
- name: Pull Docker Image of Calculator
  hosts: all

  tasks:

    - name: Pull Image
      shell: docker pull pranav243/calculator:latest

    - name: Delete existing container
      shell: docker rm Calculator

    - name: Run the container
      shell: docker create -it --name Calculator pranav243/calculator
